### ISSUE TITLE
Version Mismatches

### ISSUE THREAD

**Issue by ilivewithian** [purplebricks/Pat.DataProtection#7]
Given the following two projects:
`ConsoleApp1.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StructureMap" Version="4.5.0" />
    <PackageReference Include="Pat.Sender.DataProtectionEncryption" Version="2.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomeOtherLibrary\SomeOtherLibrary.csproj" />
  </ItemGroup>

</Project>
```

`Program.cs`
```
using log4net;
using Pat.Sender.Correlation;
using Pat.Sender.DataProtectionEncryption;
using StructureMap;
using System;
using Pat.DataProtection;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var container = new Container();
            container.Configure(c =>
            {
                c.Scan(scan =>
                {
                    scan.AssembliesFromApplicationBaseDirectory();
                    scan.WithDefaultConventions();
                });

                c.For<ICorrelationIdProvider>().Use(new LiteralCorrelationIdProvider($"{Guid.NewGuid()}"));

                c.For<ILog>().Use(s => LogManager.GetLogger(s.ParentType));
                c.For<DataProtectionConfiguration>().Use(new DataProtectionConfiguration
                {
                    AccountName = "foo",
                    AccountKey = "An Actual Account Key",
                    ApplicationName = "bar",
                    Thumbprint = "Valid Installed Certificate Thumbprint"
                });
            });

            var sender = container.GetInstance<IEncryptedMessagePublisher>();

            Console.WriteLine(sender);
        }
    }
}
```
`SomeOtherLibrary.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
  </ItemGroup>

</Project>
```
`Class1.cs`
```
namespace SomeOtherLibrary
{
    public class Class1
    {
    }
}
```

At runtime the following exception is thrown:
```
Unhandled Exception: StructureMap.Building.StructureMapBuildException: Error while building type Pat.Sender.DataProtectionEncryption.EncryptedMessagePublisher.  See the inner exception for details
1.) new EncryptedMessagePublisher(*Default of IMessageSender*, *Default of DataProtectionConfiguration*, *Default of MessageProperties*)
2.) Pat.Sender.DataProtectionEncryption.EncryptedMessagePublisher ('Pat.Sender.DataProtectionEncryption.EncryptedMessagePublisher, Pat.Sender.DataProtectionEncryption, Version=2.0.7.0, Culture=neutral, PublicKeyToken=null')
3.) Instance of Pat.Sender.DataProtectionEncryption.IEncryptedMessagePublisher ('Pat.Sender.DataProtectionEncryption.EncryptedMessagePublisher, Pat.Sender.DataProtectionEncryption,
Version=2.0.7.0, Culture=neutral, PublicKeyToken=null')
4.) Container.GetInstance<Pat.Sender.DataProtectionEncryption.IEncryptedMessagePublisher>()
 ---> System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Microsoft.AspNetCore.DataProtection.DataProtectionProvider.CreateProvider(DirectoryInfo keyDirectory, Action`1 setupAction, X509Certificate2 certificate)
   at Pat.DataProtection.DataProtectionProvider.Create(DataProtectionConfiguration config)
   at Pat.Sender.DataProtectionEncryption.EncryptedMessageGenerator..ctor(DataProtectionConfiguration configuration)
   at lambda_method(Closure , IBuildSession , IContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetInstance[T]()
   at ConsoleApp1.Program.Main(String[] args)
```

The root cause seem to be a mismatch between dependencies of 
`Microsoft.AspNetCore.DataProtection.Extensions v2.0.0` which depends on `Microsoft.Extensions.DependencyInjection v2.0.0` and 
`Microsoft.AspNetCore.DataProtection.Extensions v1.1.2` which depends on `Microsoft.Extensions.DependencyInjection`

In this example (trivialised from the original issue to aid comprehension) our application relies on another library which has a direct (non-conditional) dependency on `Microsoft.AspNetCore.DataProtection.Extensions v2.0.0`.

At runtime .net resolves to use a different assembly version of the assembly to that which was used at compile time. 

PR #6 is a potential work around, but feels clumsy. Is there a better approach?

**Comment by ilivewithian** [comment]
Fixed in #6
